---

#
# This is an example playbook that you can immediatelly use after installing the
# role from Ansible Galaxy. Just make sure to put your target hosts to appropriate
# group in your inventory file.
#
# When installing role manually by cloning directly GitHub repository please use
# following command (otherwise you may break role dependency system):
#
#   git clone https://github.com/honzamach/ansible-role-logged.git honzamach.logged
#

#
# First make sure to talk to the central syslog server(s), so that we have access
# to it`s configuration data later.
#
- hosts: server-central-logserver
  remote_user: root
  tasks:
    - name: Gather facts from all central log servers
      setup:
      delegate_to: "{{ item }}"
      delegate_facts: True
      loop: "{{ groups['server-central-logserver'] }}"

#
# Now we may proceed with configuration.
#
- hosts: servers-logged
  remote_user: root
  roles:
    - role: honzamach.logged
  tags:
    - role-logged
