---

#
# Use the delegated_facts feature to gather facts about the 'server_central_logserver' servers even in case they are not part of the play.
# Resource: https://docs.ansible.com/ansible/latest/user_guide/playbooks_delegation.html#delegated-facts
#
- name: "Inspecting configured central logservers"
  setup: {}
  delegate_to: "{{ item }}"
  delegate_facts: True
  with_items: "{{ groups['server_central_logserver'] }}"
  tags:
    - always

- name: "Ensuring the existence of subconfiguration directory"
  file:
    path: /etc/syslog-ng/conf.d
    state: directory

- name: "Configuring syslog-ng service"
  template:
    src: "{{ item }}"
    dest: /etc/syslog-ng/syslog-ng.conf
    owner: root
    group: root
    mode: 0644
    backup: yes
  with_first_found:
    - "inventory/host_files/{{ inventory_hostname }}/honzamach.logged/syslog-ng.conf.j2"
    - "inventory/group_files/servers_{{ msms_server_type }}/honzamach.logged/syslog-ng.conf.{{ ansible_lsb['codename'] }}.j2"
    - "inventory/group_files/servers_{{ msms_server_type }}/honzamach.logged/syslog-ng.conf.j2"
    - "inventory/group_files/servers/honzamach.logged/syslog-ng.conf.{{ ansible_lsb['codename'] }}.j2"
    - "inventory/group_files/servers/honzamach.logged/syslog-ng.conf.j2"
    - "syslog-ng.conf.{{ ansible_lsb['codename'] }}.j2"
    - "syslog-ng.conf.j2"
  notify: Restart syslog-ng service

- name: "Ensuring syslog-ng service is running and enabled at system start"
  service:
    name: "{{ hm_logged__service_name }}"
    state: started
    enabled: yes

- name: "Removing unnecessary logrotate configurations"
  file:
    path: "{{ item }}"
    state: absent
  with_items:
    - /etc/logrotate.d/rsyslog.disabled

- name: "Configuring logrotate for apt"
  template:
    src: "{{ item }}"
    dest: /etc/logrotate.d/apt
    owner: root
    group: root
    mode: 0644
  with_first_found:
    - "inventory/host_files/{{ inventory_hostname }}/honzamach.logged/logrotate_apt.j2"
    - "inventory/group_files/servers_{{ msms_server_type }}/honzamach.logged/logrotate_apt.{{ ansible_lsb['codename'] }}.j2"
    - "inventory/group_files/servers_{{ msms_server_type }}/honzamach.logged/logrotate_apt.j2"
    - "inventory/group_files/servers/honzamach.logged/logrotate_apt.{{ ansible_lsb['codename'] }}.j2"
    - "inventory/group_files/servers/honzamach.logged/logrotate_apt.j2"
    - "logrotate_apt.{{ ansible_lsb['codename'] }}.j2"
    - "logrotate_apt.j2"

- name: "Configuring logrotate for aptitude"
  template:
    src: "{{ item }}"
    dest: /etc/logrotate.d/aptitude
    owner: root
    group: root
    mode: 0644
  with_first_found:
    - "inventory/host_files/{{ inventory_hostname }}/honzamach.logged/logrotate_aptitude.j2"
    - "inventory/group_files/servers_{{ msms_server_type }}/honzamach.logged/logrotate_aptitude.{{ ansible_lsb['codename'] }}.j2"
    - "inventory/group_files/servers_{{ msms_server_type }}/honzamach.logged/logrotate_aptitude.j2"
    - "inventory/group_files/servers/honzamach.logged/logrotate_aptitude.{{ ansible_lsb['codename'] }}.j2"
    - "inventory/group_files/servers/honzamach.logged/logrotate_aptitude.j2"
    - "logrotate_aptitude.{{ ansible_lsb['codename'] }}.j2"
    - "logrotate_aptitude.j2"

- name: "Configuring logrotate for dpkg"
  template:
    src: "{{ item }}"
    dest: /etc/logrotate.d/dpkg
    owner: root
    group: root
    mode: 0644
  with_first_found:
    - "inventory/host_files/{{ inventory_hostname }}/honzamach.logged/logrotate_dpkg.j2"
    - "inventory/group_files/servers_{{ msms_server_type }}/honzamach.logged/logrotate_dpkg.{{ ansible_lsb['codename'] }}.j2"
    - "inventory/group_files/servers_{{ msms_server_type }}/honzamach.logged/logrotate_dpkg.j2"
    - "inventory/group_files/servers/honzamach.logged/logrotate_dpkg.{{ ansible_lsb['codename'] }}.j2"
    - "inventory/group_files/servers/honzamach.logged/logrotate_dpkg.j2"
    - "logrotate_dpkg.{{ ansible_lsb['codename'] }}.j2"
    - "logrotate_dpkg.j2"

- name: "Configuring logrotate for syslog-ng"
  template:
    src: "{{ item }}"
    dest: /etc/logrotate.d/syslog-ng
    owner: root
    group: root
    mode: 0644
  with_first_found:
    - "inventory/host_files/{{ inventory_hostname }}/honzamach.logged/logrotate_syslog-ng.j2"
    - "inventory/group_files/servers_{{ msms_server_type }}/honzamach.logged/logrotate_syslog-ng.{{ ansible_lsb['codename'] }}.j2"
    - "inventory/group_files/servers_{{ msms_server_type }}/honzamach.logged/logrotate_syslog-ng.j2"
    - "inventory/group_files/servers/honzamach.logged/logrotate_syslog-ng.{{ ansible_lsb['codename'] }}.j2"
    - "inventory/group_files/servers/honzamach.logged/logrotate_syslog-ng.j2"
    - "logrotate_syslog-ng.{{ ansible_lsb['codename'] }}.j2"
    - "logrotate_syslog-ng.j2"
